name: circlemap-env
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - circle-map=1.1.4
  - biopython>=1.80
  - sra-tools
  - samtools
  - bedops
  - bwa-mem2
  - bedtools
  - pip
  - pip:
      - -r requirements.txt