name: circlemap-env
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - sra-tools
  - samtools
  - bedops
  - bwa-mem2
  - bedtools
  - pip
  - pip:
      - circle-map
      - -r requirements.txt